name: confetti
description: Blast colorful confetti all over the screen. Celebrate in app
  achievements with style. Control the velocity, angle, gravity and amount of
  confetti.
version: 1.0.0
homepage: https://github.com/funwithflutter/flutter_confetti

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
